### ISSUE TITLE
Некорректное хранение токена

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#1]
https://github.com/anatolyukropov/CRM_TELSP/blob/0c5e2be7fd014e7b446ed6b90cdbd1c18b8e0f2c/client/src/main.js#L18

**Comment by anatolyukropov** [comment]
Переделал. Перенёс в Vue инстанс 
new Vue({
  created() {
    const token = localStorage.getItem("token");
    if (token) {
      this.$store.commit('auth_success', {token: token, user: {}});
      Vue.prototype.$http.defaults.headers.common['Authorization'] = token;
    }
  },
  router,
  store,
  render: h => h(App),
}).$mount('#app')

**Comment by starkovsky** [comment]
Речь идет о том, что токен в локалсторадже хранить не хорошо, для этого должны быть использованы секурные куки 

https://developer.mozilla.org/ru/docs/Web/HTTP/%D0%9A%D1%83%D0%BA%D0%B8#Secure_(%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D1%8B%D0%B5)_%D0%B8_HttpOnly_cookies

**Comment by starkovsky** [comment]
Secure + httpOnly

**Comment by anatolyukropov** [comment]
Понял. Переделаю.

**Comment by anatolyukropov** [comment]
Всю голову себе сломал ) Если я токен засуну в куку httpOnly, я не смогу его из Vue тогда достать. Смысл тогда в нём какой вообще ? 
Пытался сделать сессии express-mysql-session. Они создаются, пишутся в базу, всё вроде хорошо. Но почему то создаётся с одной session_id, а когда делаешь destroy() удаляется другой sessionId, которого никогда не было, и сессия остаётся висеть в таблице mysql.
Совсем запутался. Поставил пока VueSession и складирую токен туда. Но я так понимаю никак это от localstorage не отличается, ибо можно спокойно из JS достать.

**Comment by starkovsky** [comment]
В этом и прелесть httpOnly куков, они передаются только серверу и недоступны вью(Баннерам Жс, плагином браузера)

Ты должен всего лишь хранить флаг авторизации (true/false)

**Comment by anatolyukropov** [comment]
#13 Pull Request. Проблема как раз с записью cookie с сервера на vue и передача их обратно на сервер. 
Как я понял за это отвечает credentials на сервере и withcredentials на vue. НО: 
Если прописываю  в запросе при логине : 
 withCredentials: true 
 то ловлю ошибку cors 
Access to XMLHttpRequest at 'http://localhost:5000/api/users/login' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute
    Но у меня и не настроена '*' 
app.use(cors({
    origin:['http://localhost:8080'],
    methods:['GET','POST'],
    credentials: true // enable set cookie
}))

**Comment by starkovsky** [comment]
Правильно, тебе надо настроить CORS

**Comment by anatolyukropov** [comment]
#13 
Он настроен. Только коряво. Я слепой балбес )) У меня было в коде 
app.use(cors());
app.use(cors({
    origin:['http://localhost:8080'],
    methods:["GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"],
    credentials: true,
    preflightContinue : true// enable set cookie
}));

А я этого первого cors не видел. В итоге он брал options и сразу слал меня куда подальше. а я голову ломал почему в response приходит origin *

**Comment by anatolyukropov** [comment]
#13 
Всё, перелопатил вообще всю логинку и аутентификацию. 
Разобрался таки в это passport-е. У меня вообще была настроена логинка без стратегии. 
Отказался нафик от jwt, при использовании httpOnly cookie он не нужен. По крайней мере я себе не представляю как его применить.

**Comment by starkovsky** [comment]
Именно, либо jwt либо НОРМАЛЬНЫЙ httpOnly
