### ISSUE TITLE
Данная функция является логикой а не описанием роутов, тут хранить это совсем не логично

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#2]
https://github.com/anatolyukropov/CRM_TELSP/blob/0c5e2be7fd014e7b446ed6b90cdbd1c18b8e0f2c/client/src/router.js#L108

**Comment by anatolyukropov** [comment]
Согласен что не логично. Но пока что не понимаю куда её вынести. В данный момент у меня только одна функция отвечающая за логику маршрутов, выносить её в какую то отдельную папку считаю излишним, так как потом можно её не найти, а тут, всё что касается маршрутов в одном модуле, никак не проглядишь.
