### ISSUE TITLE
Такое лучше хранить в .env файлах, а не в конфиге который экспортишь в мейн жс

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#3]
https://github.com/anatolyukropov/CRM_TELSP/blob/0c5e2be7fd014e7b446ed6b90cdbd1c18b8e0f2c/client/api.config.js#L1

**Comment by anatolyukropov** [comment]
А разве в файле .env можно условия делать ? 
VUE_APP_API = process.env.NODE_ENV === "development" ?  "http://localhost:5000" : "http://10.98.16.111:5000"  
Не сработает же. 

или имеется ввиду что в .env надо сделать переменную VUE_APP_DEV_API = http://localhost:5000 и VUE_APP_PROD_API = http://10.98.16.111:5000., но тогда всё равно придётся в конфиге условием выбирать одно или другое.

**Comment by starkovsky** [comment]
Имеется ввиду, что на локалке, ты туда напишешь локалхост, а на проде айпи

**Comment by anatolyukropov** [comment]
#12 Pull request с Фиксом
