### ISSUE TITLE
Все кусочки Vuex можно и нужно мапать в компонент ...mapState, mapAction, mapGetters

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#4]
https://github.com/anatolyukropov/CRM_TELSP/blob/0c5e2be7fd014e7b446ed6b90cdbd1c18b8e0f2c/client/src/views/ExpContract.vue#L192

**Comment by anatolyukropov** [comment]
переделал всё на mapActions

**Comment by starkovsky** [comment]
Где пулреквесты?

**Comment by anatolyukropov** [comment]
А я пока о них не слышал. Сейчас буду разбираться )

**Comment by anatolyukropov** [comment]
А если я уже всё в мастер ветку закоммитил и запушил  ? Я могу ещё pull request сделать  ?

**Comment by starkovsky** [comment]
Уже нет, но ты можешь как угодно делать, пулреквесты связывают проблему(issuse) и внесение изменений (pull request)

**Comment by anatolyukropov** [comment]
`client/src/views/ProfBlank.vue`

**Comment by anatolyukropov** [comment]
[CRM_TELSP/client/src/views/ProfBlank.vue](url)

**Comment by anatolyukropov** [comment]
https://github.com/anatolyukropov/CRM_TELSP/blob/master/client/src/views/ProfBlank.vue#L348

**Comment by anatolyukropov** [comment]
#11
