### ISSUE TITLE
Если тебе надо получить состояние без изменений никакой геттер тебе не нужон

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#6]
https://github.com/anatolyukropov/CRM_TELSP/blob/0c5e2be7fd014e7b446ed6b90cdbd1c18b8e0f2c/client/src/store/modules/NavBar.js#L29

**Comment by anatolyukropov** [comment]
Убрал геттер. Взял состояние напрямую через mapState в компоненте.

**Comment by anatolyukropov** [comment]
А есть вообще смысл такие данные хранить в сторе ? Не лучше ли их прям в компоненте держать ?

**Comment by starkovsky** [comment]
В сторе нужно хранить состояние и данные которые используются в нескольких компонентах (причем речь не идет о родителе/потомке, куда данные и состояние передаются пропсами)

**Comment by starkovsky** [comment]
И нет, если ты подключил стор - это не значит что нужно все хранить в сторе

**Comment by anatolyukropov** [comment]
#14  Сделано
