### ISSUE TITLE
drawer отсутствует в твоем хранилище, что ты мутируешь непонятно

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#7]
https://github.com/anatolyukropov/CRM_TELSP/blob/0c5e2be7fd014e7b446ed6b90cdbd1c18b8e0f2c/client/src/store/modules/NavBar.js#L22

**Comment by anatolyukropov** [comment]
Убрал drawer из store. Он там не нужен. Соответственно убрал геттер из store

**Comment by anatolyukropov** [comment]
Рано закрыл )
