### ISSUE TITLE
Использовать самозакрывающиеся теги нерекомендуется

### ISSUE THREAD

**Issue by starkovsky** [anatolyukropov/CRM_TELSP#9]
https://github.com/anatolyukropov/CRM_TELSP/blob/07a6ca7216d874c40b243762223b55d3689ce561/client/src/App.vue#L3

**Comment by anatolyukropov** [comment]
Клёво. Сейчас до дома доеду попробую повторить.

**Comment by starkovsky** [comment]
Когда проблема или функционал решен и замержен, issuse должен быть закрыт
